"""empty message

Revision ID: 4dc40fcf9e3c
Revises: 
Create Date: 2025-09-25 23:54:58.539676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4dc40fcf9e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodcut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('img_nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prodcut')
    # ### end Alembic commands ###
